// ==============================================
// EXPORT
// Every format this tool emits, from the one
// resolved set.
//
// The markdown carries the most weight. An agent
// cannot hear a WAV, so parameters alone are useless
// to it — the markdown has to say when to play what,
// when NOT to, ship the synthesis function so the
// agent writes code rather than managing assets, and
// describe the relationships well enough that it can
// add a twelfth sound that belongs.
//
// Everything here reads the resolved SoundSet and
// recomputes nothing.
// ==============================================
import RUNTIME_SOURCE from "../runtime/beeps.js?raw"
import { FAMILY_BLURB, FAMILY_NAME, familyAsText } from "../shared/tools"
import { PRESETS, type PresetId } from "./presets.js"
import { DURATION_WARN_MS, frequencySpan, soundingMs } from "./resolve.js"
import {
  PAIRS,
  SOUND_SPECS,
  specFor,
  type Sound,
  type SoundId,
  type SoundSet,
} from "./sounds.js"

const round = (v: number, dp = 0) => {
  const m = Math.pow(10, dp)
  return Math.round(v * m) / m
}

/** The set as a plain data literal — what the JS export ships alongside the runtime. */
function soundsLiteral(set: SoundSet): string {
  const entries = set.sounds.map((s) => {
    const voices = s.voices.map((v) =>
      v.kind === "osc"
        ? `      { kind: "osc", waveform: ${JSON.stringify(v.waveform)}, gain: ${round(v.gain, 4)}, startOffsetMs: ${round(v.startOffsetMs, 1)},
        pitch: { startHz: ${round(v.pitch.startHz, 1)}, endHz: ${round(v.pitch.endHz, 1)}, sweepMs: ${round(v.pitch.sweepMs, 1)} },
        env: { attackMs: ${round(v.env.attackMs, 2)}, decayMs: ${round(v.env.decayMs, 2)}, sustain: ${v.env.sustain}, releaseMs: ${round(v.env.releaseMs, 2)} } }`
        : `      { kind: "noise", gain: ${round(v.gain, 4)}, startOffsetMs: ${round(v.startOffsetMs, 1)},
        env: { attackMs: ${round(v.env.attackMs, 2)}, decayMs: ${round(v.env.decayMs, 2)}, sustain: ${v.env.sustain}, releaseMs: ${round(v.env.releaseMs, 2)} } }`,
    )
    return `  ${JSON.stringify(s.id)}: {
    id: ${JSON.stringify(s.id)},
    tier: ${JSON.stringify(s.tier)},
    durationMs: ${round(s.durationMs, 1)},
    normalizedGain: ${round(s.normalizedGain, 4)},
    filter: { type: ${JSON.stringify(s.filter.type)}, cutoffHz: ${round(s.filter.cutoffHz)}, q: ${round(s.filter.q, 3)} },
    voices: [
${voices.join(",\n")}
    ],
  }`
  })
  return `{\n${entries.join(",\n")}\n}`
}

/**
 * The JS export: the runtime verbatim, plus this set as data.
 *
 * The runtime is imported with `?raw` rather than re-generated from a template,
 * so what ships is byte-for-byte the code the tool just played. A templated
 * copy would be a second implementation, and the first edit to either would
 * make the download stop matching the preview.
 */
export function toJs(set: SoundSet, url: string): string {
  return `// Generated by Beeps — ${url}
//
// Zero dependencies and zero audio assets. Everything below synthesizes at
// runtime with Web Audio.
//
// Sound is OFF until you call enable(), and enable() must run inside a real
// user gesture or the browser hands back a suspended context. Persist that
// choice per user; never turn it on for them.
//
//   import { createBeeps, SOUNDS } from "./beeps.js"
//   const beeps = createBeeps({ sounds: SOUNDS })
//   settingsToggle.addEventListener("click", () => beeps.enable())
//   button.addEventListener("click", () => beeps.play("tap"))

export const SOUNDS = ${soundsLiteral(set)}

${RUNTIME_SOURCE}`
}

/** The full resolved set, for anything that would rather parse than read. */
export function toJson(set: SoundSet, url: string): string {
  return JSON.stringify(
    {
      $schema: "https://beeps.studio/schema/v1",
      generator: "Beeps — beeps.studio",
      source: url,
      preset: set.presetId,
      baseHz: round(set.baseHz, 1),
      sounds: set.sounds.map((s) => ({
        id: s.id,
        tier: s.tier,
        durationMs: round(s.durationMs, 1),
        soundingMs: round(soundingMs(s), 1),
        normalizedGain: round(s.normalizedGain, 4),
        frequencyHz: {
          min: round(frequencySpan(s).minHz),
          max: round(frequencySpan(s).maxHz),
        },
        filter: {
          type: s.filter.type,
          cutoffHz: round(s.filter.cutoffHz),
          q: round(s.filter.q, 3),
        },
        voices: s.voices.map((v) =>
          v.kind === "osc"
            ? {
                kind: v.kind,
                waveform: v.waveform,
                gain: round(v.gain, 4),
                startOffsetMs: round(v.startOffsetMs, 1),
                pitch: {
                  startHz: round(v.pitch.startHz, 1),
                  endHz: round(v.pitch.endHz, 1),
                  sweepMs: round(v.pitch.sweepMs, 1),
                },
                env: v.env,
              }
            : { kind: v.kind, gain: round(v.gain, 4), env: v.env },
        ),
        when: specFor(s.id).when,
        whenNot: specFor(s.id).whenNot,
      })),
      notes: [
        "All sound is synthesized at runtime. There are no audio assets.",
        "Every export must sit behind a mute gate that defaults to off.",
        `Sounds are derived at musical intervals from baseHz (${round(set.baseHz)} Hz), so nothing in the set clashes.`,
      ],
    },
    null,
    2,
  )
}

/** WAV plus the snippet that plays it, for the iOS side. */
export function toNative(sound: Sound, url: string): string {
  return `// ${sound.id}.wav — generated by Beeps
// ${url}
//
// Download the WAV from the same panel and add it to your bundle.
// Mono, 16-bit, 44.1 kHz.

import AVFoundation

final class Beeps {
    /// Off until the user asks. Persist this; never default it to true.
    static var isEnabled = false

    private static var players: [String: AVAudioPlayer] = [:]

    /// Call once at launch. .ambient means UI sound never stops someone's music.
    static func configure() {
        try? AVAudioSession.sharedInstance().setCategory(.ambient, mode: .default)
        try? AVAudioSession.sharedInstance().setActive(true)
    }

    static func play(_ name: String) {
        guard isEnabled else { return }
        if let cached = players[name] {
            cached.currentTime = 0
            cached.play()
            return
        }
        guard let url = Bundle.main.url(forResource: name, withExtension: "wav"),
              let player = try? AVAudioPlayer(contentsOf: url) else { return }
        player.prepareToPlay()
        players[name] = player
        player.play()
    }
}

// Beeps.play("${sound.id}")
`
}

// ---------------------------------------------------------------------------
// The agent markdown
// ---------------------------------------------------------------------------

function characterSentence(set: SoundSet): string {
  const preset = PRESETS[set.presetId as PresetId]
  if (!preset) return `Base ${round(set.baseHz)} Hz.`

  // Describe the stack, because on most presets that IS the character — a
  // waveform name alone would make Warm and Bloopy sound identical on paper.
  const stack = preset.layers
    .map((l) => {
      const at =
        l.interval === 0
          ? l.detuneCents
            ? `detuned ${l.detuneCents} cents`
            : "at the note"
          : `+${l.interval} semitones`
      const rings = l.tail && l.tail > 1 ? ", ringing on" : ""
      return `${l.waveform} ${at}${rings}`
    })
    .join("; ")

  const noise = preset.noise ? `, plus a ${preset.noise.decayMs} ms noise transient` : ""
  const glide = preset.glide === "stepped" ? ", pitch stepping rather than sliding" : ""
  return (
    `${preset.name} — ${stack}${noise}. Base ${round(set.baseHz)} Hz, ${preset.attackMs} ms attack, ` +
    `${preset.filterType} at ${round(preset.filterCutoffHz)} Hz with Q ${preset.filterQ}${glide}. ` +
    `Suits ${preset.suits}.`
  )
}

function intervalOf(set: SoundSet, id: SoundId): string {
  const sound = set.sounds.find((s) => s.id === id)
  if (!sound) return ""
  const osc = sound.voices.filter((v) => v.kind === "osc")
  if (!osc.length) return ""
  const semis = (hz: number) => Math.round(Math.log2(hz / set.baseHz) * 12)
  return osc
    .map((v) => {
      if (v.kind !== "osc") return ""
      const from = semis(v.pitch.startHz)
      const to = semis(v.pitch.endHz)
      const sign = (n: number) => (n >= 0 ? `+${n}` : `${n}`)
      return from === to ? sign(to) : `${sign(from)} → ${sign(to)}`
    })
    .join(", then ")
}

export function toAgentMarkdown(set: SoundSet, url: string, warnings: string[] = []): string {
  const lines: string[] = []

  if (warnings.length) {
    lines.push(
      "> **This link did not arrive intact.**",
      ...warnings.map((w) => `> ${w}`),
      "> Everything below describes what survived, which may not be the set that was shared.",
      "",
    )
  }

  lines.push(
    "# UI sounds",
    "",
    `Source: ${url}`,
    "",
    `**Character.** ${characterSentence(set)}`,
    "",
    "All eleven sounds are synthesized at runtime with Web Audio. There are no audio",
    "files, no sample library and nothing to license. The whole set is the data below",
    "plus the function further down.",
    "",
    "## The set",
    "",
    "| Sound | Tier | ms | Interval | When to play it | When NOT to |",
    "| --- | --- | --- | --- | --- | --- |",
  )

  for (const spec of SOUND_SPECS) {
    const sound = set.sounds.find((s) => s.id === spec.id)
    if (!sound) continue
    lines.push(
      `| \`${spec.id}\` | ${spec.tier} | ${Math.round(soundingMs(sound))} | ${intervalOf(set, spec.id)} | ${spec.when} | ${spec.whenNot} |`,
    )
  }

  lines.push(
    "",
    "The *When NOT to* column is the important one. The failure mode of UI sound is",
    "not a bad sound — it is a good sound played too often. Wiring these to every",
    "event you can find is how an interface becomes something people mute.",
    "",
    "## Requirements",
    "",
    "1. **Ship a global mute gate, and default it to OFF.** The user opts in once,",
    "   the choice persists, and nothing plays before they do. This is not a",
    "   suggestion — an app that makes noise unasked gets muted at the OS level by",
    "   someone who will never turn it back on.",
    "2. **Never autoplay.** No sound on page load, on route change, or on anything",
    "   the user did not initiate.",
    "3. **Start the AudioContext inside a real user gesture.** A context created on",
    "   load lands suspended, and every later `play()` silently does nothing.",
    "4. **One sound per event, not one per item.** A batch of ten arrivals plays",
    "   `receive` once.",
    "5. **Respect the platform mute switch.** On iOS use the `.ambient` audio",
    "   session category so UI sound never interrupts someone's music.",
    "",
    "## How the set fits together",
    "",
    `Everything derives from one base frequency of **${round(set.baseHz)} Hz**. Each sound sits at a`,
    "musical interval from it, so no two sounds clash when they overlap during fast",
    "interaction. To add a twelfth sound, pick an interval from the table above that",
    "is not taken, put it in the tier that matches how much attention the event",
    "deserves, and follow these rules:",
    "",
    "- **Direction is meaning.** A rising sweep reads as confirmation or departure; a",
    "  falling one as dismissal, arrival or removal. Never invert one to save work.",
    "- **Pairs are inversions.** " +
      PAIRS.filter((p) => p.kind === "inversion")
        .map((p) => `\`${p.a}\`/\`${p.b}\``)
        .join(", ") +
      " are the same sound with the",
    "  sweep reversed. If you add a paired concept, build the second from the first.",
    "- **`success` and `error` are NOT an inversion.** They contrast in consonance: a",
    "  consonant rise against a dissonant fall. Inverting `success` would produce a",
    "  falling fourth, which is already `notification`.",
    "- **Tiers move gain and duration together.** subtle < notable < alert. A louder",
    "  sound that is also longer is twice as intrusive.",
    `- **Stay under ${DURATION_WARN_MS} ms.** Longer UI sounds overlap the next interaction and`,
    "  make an interface feel slow in a way people blame on performance.",
    "",
    "## Frequency guidance",
    "",
    "| Zone | Range | Why it matters |",
    "| --- | --- | --- |",
    "| Phone-speaker floor | below ~300 Hz | Micro-speakers produce little output here. A sound with its energy down there is inaudible on the device most people hold. |",
    "| Harsh band | 2–5 kHz | The ear's most sensitive region. Peaks here read as piercing at volumes that seem fine elsewhere. |",
    "| Dead air | above ~12 kHz | Inaudible to many adults and pure file size. |",
    "",
    `This set spans ${round(Math.min(...set.sounds.map((s) => frequencySpan(s).minHz)))} Hz to ${round(Math.max(...set.sounds.map((s) => frequencySpan(s).maxHz)))} Hz, clear of all three.`,
    "",
    "The set is loudness-normalized with A-weighted RMS within each tier, so no sound",
    "spikes relative to its siblings. `normalizedGain` carries that measurement — do",
    "not drop it, or the levelling is lost.",
    "",
    "## The code",
    "",
    "Take the **JS** tab from the same export panel. It contains this exact set as a",
    "data literal plus the synthesis runtime — the same code that produced what was",
    "previewed, shipped verbatim rather than regenerated. Do not build an asset",
    "pipeline; there are no assets.",
    "",
    "```js",
    'import { createBeeps, SOUNDS } from "./beeps.js"',
    "",
    "const beeps = createBeeps({ sounds: SOUNDS })",
    "// Inside a real user gesture, and only once the user has opted in:",
    "beeps.enable()",
    'beeps.play("tap")',
    "```",
    "",
    "WAV files and inline data URIs are available in the same panel if a platform",
    "needs them, but the JS export is the one to reach for on the web: it ships no",
    "assets and makes no network request.",
    "",
    "## Changing this set",
    "",
    "Every parameter is optional; with none you get the default preset.",
    "",
    "```",
    "p    Character preset: soft | crisp | minimal. Default soft.",
    "b    Base frequency in Hz, 220-2000. All eleven sounds move with it.",
    "",
    '<sound>   One key per edited sound, fields separated by ".". The key is the',
    "          sound id with any dot replaced by a hyphen, so `toggle.on` is",
    "          written `toggle-on`. Fields:",
    "            f<hz>   sweep start frequency",
    "            e<hz>   sweep end frequency",
    "            a<ms>   attack        d<ms>   decay        r<ms>   release",
    "            n<ms>   duration      g<db>   gain trim (negative is quieter)",
    "            c<hz>   filter cutoff q<n>    resonance x10, so q7 is Q 0.7",
    "",
    "Example: ?p=crisp&b=760&tap=f900.a2&error=g-3",
    "```",
    "",
    "Pitch on the derived half of an inversion pair is stored on the canonical half",
    "instead — editing `close` writes to `open`. That is deliberate: it means the two",
    "cannot be set to disagree.",
    "",
    "## Other tools in this family",
    "",
    `${FAMILY_NAME} — ${FAMILY_BLURB}`,
    "",
    "```",
    familyAsText("sound"),
    "```",
    "",
  )

  return lines.join("\n")
}
